package EchoesOfTheOath.UI;

public class DialogueManager {
    
    public static String getIntroDialogue() {
        return "Long ago, three adventurers—a brave warrior, a swift archer, and a wise mage—" +
               "traveled across worlds, earning fame for vanquishing great evils. " +
               "Their bond was unbreakable, their deeds legendary...";
    }

    public static String[] getNationDialogue(int nation) {
        return switch (nation) {
            case 1 -> new String[] {
                "",
                "(You walk along a dirt path toward the outskirts. The air is thick with the smell of wet stone and smoke.)", 
                "Humanas. From a distance, the walls look strong. Up close, they're just holding up a graveyard.",
                "Gates are broken. Guards look half-starved. This isn't a kingdom; it's a cage.",
                "(You enter the city. The streets are empty. No trade, no talk—only the sound of your footsteps on the stone.)",
                "(A Gatekeeper sits on a crate, tiredly sharpening a rusted blade. He looks up as you approach.)", 
                "“Whatever you’re looking for, traveler, we don't have it. Food’s gone. Gold’s gone. Move on.”", 
                "“Where is everyone? The streets are dead.”", 
                "Hiding. Collectors are making their rounds. If you want to keep that gear, stay out of the light. They take everything to the castle for the ‘King’s blessing.",
                "The King’s blessing. In a place this miserable, that sounds like a threat.",
                "(You walk into the central plaza. Rows of empty gallows line the square, and in the center stands a massive, polished gold statue of a toddler—**King Bartholomew**—shining unnaturally against the grey buildings.)",
                "(A **cloaked man** stands by the statue, watching you.)",
                "“Beautiful, isn't it? A golden boy for a leaden kingdom”",
                "“Why is a golden child standing in the middle of a slum?”",
                "“That’s King Bartholomew. Or at least, the version they want us to see. Every coin stolen from these streets goes into that castle to keep him 'happy.' They say he hasn't aged a day in years. They say his voice can stop your heart.”",
                "“A child king who never grows up... and steals from his own people. I need to see him for myself.”",
                "“Many do. None come back. If you’re that eager to lose your head, go to the Old Chapel. That’s where the collectors bring the 'offerings' before they head to the castle. You’ll find a way in there—if the guards don’t find you first.”",
                "(The Informant slips away into a side street.)",
                "“A child king who doesn't age. There’s something wrong with that throne.”",
                "“The 'Old Oath' is pulling at me. It’s not just curiosity anymore. I need to know who—or what—is actually wearing that crown.”",
                "(You reach the Chapel. The doors are barred with heavy iron. There’s no singing inside—only the cold sound of metal coins being sorted and the occasional muffled shout.)",
                "“The Chapel is just a counting house now. But it’s the only path that leads to the castle.”",
                "“Bartholomew... let's see if you're as golden as your statue.”",
                "\"The castle is too quiet. No servants, no life. Just the sound of my own breath.\"",
                "\"They say King Bartholomew hasn't spoken a word in years, yet his decrees have starved half the nation.\"",
                "\"Someone is whispering to be standing behind the silk curtains. Someone who remembers every debt this city owes.\"",
                "(The room is massive. Thick curtains block all natural light. In the center, a golden crib sits atop a high marble dais. Two masked Attendants stand perfectly still behind it.)",
                "“You aren't on the guest list, traveler.”",
                "“I’m not here for a party. I’m here to talk to the King.”",
                "“The King doesn't 'talk.' He decides. And according to the records, your life is currently in arrears.”",
                "“Who’s writing those records? The boy can’t even hold a pen.”",
                "“His Majesty is... displeased with your tone.”",
                "(Inside the crib, the toddler sits up. His eyes are milky and vacant, glowing with a green light. He doesn't cry or scream. The massive crown on his head hums, and the shadows of the pillars begin to crawl across the floor like living ink.)",
                "\"That’s not a child’s anger. That’s a programmed response.\"",
                "\"Whatever is in that crown is using him like a conduit.\"",
                "“The decree is signed. Clear the debt.”",
                "(You draw their weapon as the shadows solidify into tall, faceless sentinels.)",
                "(The shadows melt back into the floor. The red glow leaves the child’s eyes, and he collapses back into the pillows, looking small and exhausted. The attendants have vanished into the dark corners of the room.)",
                "“He’s just a kid. He didn't even know he was fighting.”",
                "(You reach into the crib. The boy doesn't pull away; he just stares, confused. Your pendant pulses with a cold, warning light.)",
                "\"The 'King' is an empty shell. He wasn't the one signing those death warrants.\"",
                "\"The Attendants weren't looking at the boy for orders—they were looking at the shadows behind the throne.\"",
                "“The library. The Gatekeeper mentioned a place where the 'debts' are kept.”",
                "“If the King isn't the one pulling the strings, then I’ve been hunting the wrong man.”",
                "(You look at a trail of black ink leading from the base of the throne toward a heavy, reinforced trapdoor in the floor.)",
                "\"The records. Every coin, every soul, every drop of blood... it all leads down there.\"",
                "\"To the one who keeps the books.\"",
                " “Your oath was to protect the innocent… find the one who stole his voice.”",
                "(A single candle flickers in the distance, revealing a pair of unblinking eyes watching you...)",
                "(You go down a tight spiral staircase. The walls are stained with black ink that seems to pulse. The sound of a scratching quill fills the air, echoing like a heartbeat.)",
                "(A massive, cold vault. Rows of scrolls stretch into the dark. The Archivist sits behind a desk of stacked parchment. He doesn't move; only his eyes follow you.)",
                "“You’ve caused a lot of damage upstairs. My ledger hasn't been this messy in centuries.”",
                "“The King is a puppet. You’ve been using a child to bleed this city dry.”",
                "“I don't use anyone. I record. If a King chooses to let his fear dictate the law, I simply write it down. The people of Humanas are a collection of debts. I am the only one who ensures they aren't forgotten.”",
                "“At the cost of their lives? That’s not a record. It’s a prison.”",
                "“Truth is a weight most can't carry. You should know that better than anyone, Wanderer. Your own story is nothing but torn pages and broken promises.”",
                "(You wince. A flash of white light hits their mind: three shadows standing, and a looming darkness that swallowed them all. You grip your head.)",
                "The others... where are they? Why does it feel like I left something behind?”",
                "“Forgetfulness is a mercy. But the ink remembers. Let’s see what yours says about your ending.”",
                "(The Archivist stands, his robes unfurling like thousands of sharp scrolls. You're panting, leaning on your weapon.)",
                "“The records demand completion! You cannot run from a debt you’ve already signed!”",
                "(A scroll flies past your face. For a split second, they see a word written in glowing light: *ELARION*.)",
                "“That name... I’ve heard it before. In the dream. We were supposed to... we were supposed to bind it.”",
                "(Your pendant glows with a violent, flickering light. A voice, distant and distorted, echoes in their mind.)",
                "“We vow to bind the darkness... within ourselves...”",
                "“The oath... it’s not just a story. It’s why I’m here. I didn't just survive. I failed.”",
                "(Your weapon ignites with a raw, unstable energy. They lung forward, driving the blade through the center of the Archivist’s desk and into his chest.)",
                "(The library begins to dissolve into ash. The scrolls turn into black flakes that drift toward the ceiling.)",
                "“You think... freeing them... changes anything? You only broke... one link... in a chain... you helped forge.”",
                "“Maybe. But I’m the one who’s going to break the rest.”",
                "(The Archivist vanishes. You pick up a single blank page. Their hand is shaking.)",
                "\"The library is gone, but the weight in my chest is heavier than ever.\"",
                "\"I saw faces in those scrolls. Faces I should know....\"",
                "\"Whatever we promised to do, we didn't finish it. This nation was just the start.\"",
                "(You look up. The sun shines through the rubble. Far off in the distance, across the sea, a purple forest glows on the horizon.)",
                "“Veyora. The Elves. If the fragments of what I lost are there... I have to find them.”",
                "(Your vision fades to black as you walks toward the light.)"
            };

            case 2 -> new String[] { 
                "(You stand at the edge of a forest where the leaves are a deep, bruised purple. Pale light drifts like snow, but the air feels heavy.)", 
                "\"Veyora. They say these woods were once the lungs of the world.\"" ,
                "\"Now, the air tastes like copper and old grudges. The roots aren't growing; they're strangling.\"",
                "(Your pendant pulses—a cold, sharp throb. A flash of memory hits: a golden gate, a tall figure in green, and a vow spoken in unison. You stumble.)",
                "\"That vow... we promised to keep the dark inside. But I woke up empty. Did I leave them behind, or did they leave me?\"",
                "(You enter a clearing where elven structures are being overtaken by jagged, dark vines. Two Elven warriors are in a heated standoff.)",
                "\"Lunareth is the Warden! His word is the forest's will. You're a traitor for questioning the tithe!\"",
                "\"The 'will' is rotting the trees, Scout. He’s feeding the Root our lifeblood. Look around you!\"",
                "(They notice you. Their hands move to their hilts.)",
                "\"I’m looking for the one in charge. Lunareth.\"",
                "\"You and every other fool seeking a miracle. You won't get past the Eastern Grove.\"",
                "\"The Warden doesn't see outsiders. And if he did, **Ilaryx** would have your head before you stepped foot in the inner circle.\"",
                "\"Ilaryx?\"",
                "\"The Silverfang. The Warden’s shadow. She doesn't talk to trespassers—she hunts them. If you’re smart, you’ll turn back now.\"",
                "\"The Silverfang. They speak her name with a mix of worship and terror.\"",
                "\"If she’s the one guarding the path to Lunareth, then she’s the one I need to find.\"",
                "(You move into the deep woods. The mist thickens, turning a sickly violet. Whispers begin to overlap.)",
                "\"You let the balance break... you let us fall...\"",
                "\"It’s just the mist. Fragments of a dream I can't finish.\"",
                "(A shadow flashes between the trees—faster than a human. A silver glint catches the light. A notched arrow thuds into a tree inches from your head.)",
                "\"Show yourself!\"",
                "(No answer. Only the sound of something heavy moving through the canopy. You realize they aren't just traveling anymore; they are being stalked.)",
                "(You find a small, protected grove. An old Elf with grey-streaked hair is tending to a tree that is bleeding black sap.)",
                "\"Don't stand so close to the path. Her arrows don't miss twice.\"",
                "\"You mean Ilaryx? I’m looking for her. And the 'Tear of Veyora'.\"",
                "\"You’re either very brave or very tired of living. Ilaryx was the best of us. Now she’s just a weapon forged from Lunareth’s paranoia.\"",
                "\"I saw the corruption in the Humanas King. Is it the same here? Is she being controlled?\"",
                "\"Worse. She believes in the cause. She thinks mercy is a weakness that will kill the forest. But I’ve seen her eyes when she thinks no one is looking. She’s doubting.\"",
                "\"Then I’ll give her a reason to stop. Where is she?\"",
                "\"Deep in the Silvergrove. She guards the Tear. But remember, traveler... she isn't a monster. She’s a hunter who’s lost her way. If you can’t break her resolve, she’ll bury you beneath these roots.\"",
                "\"Precision. Loyalty. Doubt. I know what it feels like to follow a path that's crumbling beneath your feet.\"",
                "\"I’m coming for you, Silverfang. Let’s see if your arrows are as sharp as your regrets.\"",
                "(The sound of a bowstring being drawn tight echoes through the speakers.)",
                "(You leave the Healer’s Grove. The dense, violet mist of the \"Whispers\" quest begins to thin, revealing a clearing of massive, bleached-white trees.)",
                "\"The mist is gone, but the air is heavier here.\"",
                "\"In Veyora, silence isn't peace. It’s a warning.\"",
                "(You step into the center of the glade. A silver arrow thuds into the earth inches from their boot. Then another. You stop.)",
                "\"I know you're there. The Healer said you’d be waiting.\"",
                "(Ilaryx drops from a high branch, landing silently. She stands tall, her silver hair contrasting with the dark, pulsing veins on her neck. She keeps her bow raised, an arrow notched and aimed at your throat.)",
                "\"The Healer is a fool. She thinks a stranger can fix a forest that’s already been judged.\"",
                "\"I’m just looking for the Tear of Veyora. And the man who's hoarding it.\"",
                "\"The Warden doesn't 'hoard.' Lunareth preserves. Without his grip, the factions would have burnt this woods to ash years ago. Fear is the only thing keeping the Elves from extinction.\"",
                "\"Look at the trees, Ilaryx. They’re choking. If this is his 'preservation,' there won't be a forest left to rule.\"",
                "\"Survival isn't pretty, traveler. Lunareth taught me that. Weakness is the only sin left in Veyora.\"",
                "\"Then let's see how strong his teachings really are.\"",
                "(Ilaryx narrows her eyes. The silver glow of her bow intensifies, reflecting in the crimson tint of her pupils.)",
                "\"Don't expect mercy. I ran out of that a long time ago.\"",
                "(The battle ends. Ilaryx’s bow is cracked. she is on one knee, breathing heavily. The dark veins on her skin are receding, leaving her pale and exhausted. You stand over her, weapon lowered.)",
                "\"Finish it. That's... the law of the woods.\"",
                "\"I'm not here for your life. I'm here for the Tear.\"",
                "(Ilaryx reaches into a pouch at her belt and pulls out a glowing, crystalline drop of sap. She sets it on the mossy ground between them.)",
                "\"You’re making a mistake. Lunareth won't be as... hesitant as I was. He stopped believing in 'balance' the day the war started. Now, he only believes in the blade.\"",
                "\"He was a Guardian once. I remember that much. What changed him?\"",
                "\"He decided that being an executioner was better than being a victim. He’s waiting for you at the Heart of the Bough. He’s already judged you, traveler. He just hasn't carried out the sentence yet.\"",
                "\"The Warden. The Executioner. The names change, but the smell of the rot is the same.\"",
                "\"The 'Oath' we took... it was supposed to bind the darkness. Instead, it looks like it just gave Lunareth an excuse to become it.\"",
                "\"I’m coming for the truth, Warden. Whether you’re ready to give it or not.\"",
                "(You walk past Ilaryx towards the giant tree at the center of the horizon. The sky turns a deep, bruised purple as thunder rolls over the forest.)",
                "\"Ilaryx stayed behind in the shadows. She didn't follow, but she didn't stop me either.\"",
                "\"The forest is holding its breath. The judge is on his throne, and the trial is about to begin.\"",
                "(In the high balcony of the World Tree, a tall, imposing silhouette in ornate elven armor looks down at the forest below.)",
                "\"So... the survivor returns. Let’s see if you’ve learned anything since the fall.\"",
                "(After the fight with Ilaryx, You use the Tear of Veyora. The glowing sap melts into the roots of the Silverglade, forcing the massive thorns blocking the path to the World Tree to retract.)",
                "(You walk toward the trunk of the Citadel—a fortress made of living, calcified wood.)",
                "\"The forest has gone completely quiet. No wind, no whispers. Just the sound of the Heart beating beneath the soil.\"",
                "\"Ilaryx was just the gatekeeper. The man at the top of these roots is the one who let the rot in.\"",
                "(You enter the throne room. It’s an open-air platform at the very peak of the World Tree. Lunareth stands at the edge, looking out over the darkened forest. He doesn't turn around immediately. He looks tired, his armor etched with the same black veins seen on the trees.)",
                "\"Ilaryx failed, then. I told her loyalty was a weight she couldn't carry.\"",
                "\"She didn't fail. She just realized you weren't worth dying for.\"",
                "\"You speak as if you remember what worth is. We stood at the Gate together. We swore to bind the dark. And then you fell, and left me to manage the ruin.\"",
                "\"I don't remember the Gate. But I see what you've done here. This isn't 'management.' It's a slow death.\"",
                "\"I did what was necessary to keep the Elves from tearing each other apart. If they have to fear me to survive, then I will be their nightmare. It's a small price for order.\"",
                "\"Then you've already lost the forest, Warden.\"",
                "(The moon above the tree turns a sickly crimson. Lunareth draws his string, the air around him vibrating with raw energy.)",
                "(The battle ends. Lunareth is slumped against the central trunk. His bow lies in splinters. The black veins on his skin are pulsing violently, then shattering like glass.)",
                "\"The darkness... it was so much heavier than we thought. I thought I could contain it by ruling it. I was wrong.\"",
                "\"You weren't meant to carry it alone.\"",
                "\"Maybe. But it's too late for me. The roots are calling back what’s left.\"",
                "(Lunareth’s body begins to dissolve into silver motes, drifting into the bark of the World Tree. The oppressive violet mist in the distance begins to clear.)",
                "\"Rest, Lunareth. I’ll take it from here.\"",
                "\"The Warden is gone. The forest is breathing again, but the air is still cold.\"",
                "\"He mentioned the Gate. He mentioned 'us.' I’m starting to see the shapes of the people I lost... but the fog in my head hasn't lifted yet.\"",
                "(You stand at the edge of the Citadel. In the far distance, past the elven borders, the sky is no longer purple or blue. It is a harsh, burning red. Jagged volcanic peaks pierce the clouds.)",
                "\"Veyora is safe for now. But the source of the rot didn't start here.\"",
                "\"The 'Oath' is pulling me toward the iron gates of the south. Toward the smoke.\"",
                "\"The Nation of Demons. If the truth is buried anywhere, it’s in the fire.\"",
                "(Over the ocean toward a land of black rock and flowing lava. A deep, demonic growl echoes through your ears.)"
            };
            
            case 3 -> new String[] { 
                "(You stand at the edge of a jagged chasm. The sky is a bruised, permanent red; ash falls like snow. Across the void sits the Umbral Fortress—a monolith of black glass that seems to swallow the light around it.)",
                "\"The Umbral Fortress. It doesn't just look cold; it feels empty. Like a hole in the world.\"",
                "\"This is where the line was drawn. This is where the they fell. This is where I broke.\"",
                "\"I can feel the Oath splintering in my chest. It’s not a memory yet... it’s just a scream I can't quite hear.\"",
                "(As you step onto a bridge of shifting shadow, two faint, flickering silhouettes appear: The Archivist and Lunareth. They look diminished, their forms fraying.)",
                "\"He’s still there. Guarding a gate that’s already been kicked open.\"",
                "\"Sarukdal was the shield. He didn't have the luxury of forgetting, like you did. He’s been awake for every second of the last thousand years.\"",
                "\"If he’s still there, maybe I can talk to him.\"",
                "\"You can't talk to a landslide. You can only survive it.\"",
                "(The spirits vanish. You enter the fortress.)",
                "(The interior is a silent maze. On the walls, the shadows move independently, replaying a flickering scene: Four figures—you, The Archivist, Lunareth, and a massive, armored Sarukdal—standing before a blinding rift.)",
                "\"I will be the wall. Let the void break against me. I will not move.\"",
                "(You fall. The Oath shatters. The shadow rushes into Sarukdal, who doesn't run—he stands his ground even as his armor melts and fuses to his skin, his scream echoing into the present.)",
                "\"He didn't move. He did exactly what he promised.\"",
                "\"My failure didn't just break the world. It trapped him in a cage of his own loyalty.\"",
                "\"Elarion didn't have to conquer Sarukdal. He just had to wait for Sarukdal's devotion to turn into rot.\"",
                "(A deep, vibrating growl echoes from the chamber ahead. It’s the sound of grinding tectonic plates.)",
                "\"THE TRAITOR RETURNS. THE ONE WHO SLEPT WHILE WE BURNED.\"",
                "(You enter a cathedral-sized vault. In the center, SARUKDAL is kneeling. He is a mountain of blackened iron and pulsing veins. His shield is no longer a tool; it has grown into his arm, massive and jagged.)",
                "(The path is blocked by a rift of pure shadow. A voice—Sarukdal’s original voice—speaks from the darkness.)",
                "\"What is the weight of a shield that protects nothing?\"",
                "\"Guilt.\"",
                "\"What is the fate of a promise made by a ghost?\"",
                "\"Silence.\"",
                "\"What do you owe the ones you left behind?\"",
                "\"Everything.\"",
                "(The shadow solidifies into a bridge. you cross it, stepping onto the dais. Sarukdal rises slowly. He is twice the height of you, his presence blotting out the red sky above.)",
                "\"You forgot. You fell, and you chose the mercy of silence. I stayed. I felt every crack in the world. I felt the their light go out, and their mind shatter.\"",
                "\"I didn't choose to forget, Sarukdal. But I’m here now.\"",
                "\"Too late. The shield is broken, but the wall remains. You aren't here to save me. You’re just here to be the last name I strike from the ledger.\"",
                "\"There is no more talking. He’s not a man anymore; he’s the physical manifestation of my own regret.\"",
                "\"To reach Elarion, I have to break the only thing that actually stayed true to me.\"",
                "(Sarukdal rips his shield from the floor. The metal screams as shadow energy bleeds from the cracks.)",
                "",
                "(Sarukdal falls to one knee. The black veins on his armor shatter, dissolving into grey mist. He looks human again—smaller, tired, and dying.)",
                "\"You actually came back.\"",
                "\"I did. I'm sorry it took this long.\"",
                "\"I couldn't hold it, Hero. The despair... it was louder than the Oath. I let him in.\"",
                "\"Elarion. Where is he?\"",
                "\"The Unbound Throne. Where it started. He’s feeding on the shards of what we used to be.\"",
                "(Sarukdal’s hand drops. He dissolves into silver light, leaving only his cleansed shield behind. As the light hits you, the final fragments of memory snap into place.)",
                "\"Elarion is waiting at the Unbound Throne. But the air here is warping.\"",
                "\"The shadows are bleeding into the stone, pulling me down into my own memories. The Shadow Realm.\"",
                "\"It's so cold... and my light is dying.\"",
                "(The black spire of the fortress. At the very top, the sky has torn open into a jagged violet rift. A silhouette sits on a throne of floating obsidian, watching you move upward.)",
                "\"The Archivist’s knowledge. Lunareth’s nature. Sarukdal’s strength.\"",
                "\"He took it all. He used my friends to build his kingdom.\"",
                "\"Now, there’s nothing left between us but a thousand years of lies.\"",
                "\"Elarion. It’s time to face the truth.\"",
                "(Your surroundings vibrate with a low, cosmic hum. A massive eye opens within the rift above the throne.)",
                "\"Welcome home... Echo.\"",
                "(You ascend the final obsidian stairs. The air is non-existent. There is no sound except for two heartbeats in perfect sync. A throne made of nothingness, and sitting upon it is a figure identical to you, but carved from shifting shadows.)",
                "\"The throne room. This is where it started. Where we gave up our lives to build a cage.\"",
                "\"And there he is. He isn't a demon. He’s the silence between my words. He’s the shadow I forgot to watch.\"",
                "\"You’re finally whole. I should thank you. I fed on the others—their fear and their pride. But your guilt... that was the strongest ink of all.\"",
                "\"The cage is gone, Elarion. But I’m still standing.\"",
                "\"You're standing in a graveyard you built. The 'Oath' was a temporary fix. Your fall gave me the key, and now I am the only truth left.\"",
                "\"I didn't come here to destroy you. I came to fulfill the promise.\"",
                "\"You have nothing left to give. I am the shadow you cast. To kill me is to kill yourself.\"",
                "\"The Oath wasn't about killing the dark. It was about balance.\"",
                "\"There is no balance. Only the void.\"",
                "(Elarion stands. His shadow-form ripples and expands, mimicking your stance perfectly.)",
                "(The energy stops. The two forms—Hero and Shadow—are inches apart. You reach out and grab Elarion’s wrists.)",
                "\"What are you doing? Let go... this will end us both.\"",
                "\"The Oath was broken. Now, it's re-sworn.\"",
                "(Your pendant shatters in a burst of white light. Instead of pushing Elarion away, you pull the shadow into your own chest.)",
                "\"You aren't meant to be destroyed. You're meant to be carried.\"",
                "\"I will be the cage. I will be the guardian.\"",
                "(A blinding white light consumes your vision. The Umbral Fortress dissolves into dust. The red sky of the Demon Realms clears, revealing a pale, morning blue.)",
                "(You stand in a green field. The sun is rising. Faint, glowing lines of gold and silver energy are etched into your skin.)",
                "\"He’s quiet now. The void is still there, but it’s balanced.\"",
                "\"The others are gone, but their memories are safe. They’re part of me now.\"",
                "\"My journey to remember is over.\"",
                "\"My journey as the Guardian has just begun.\"",
                "", "", "", "", "", "", "", "", ""
            };

            default -> new String[] { "" };
        };
    }
}